name = "tank-game"
main = "workers/index.ts"
compatibility_date = "2026-05-02"
routes = [{ pattern = "tankgame.wildcat.io", custom_domain = true }]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[durable_objects.bindings]]
name = "TANK_ROOMS"
class_name = "TankRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TankRoom"]
